server.port=8080

# Basic Application Configuration
spring.application.name=the-collector-backend

# PostgreSQL Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/thecollectordb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# JWT Configuration
application.security.jwt.secret-key=${JWT_SECRET:una_clave_secreta_por_defecto_extra_extensa_123456789}
application.security.jwt.expiration=${JWT_EXPIRATION:86400000}
