server.port=8080

# Basic Application Configuration
spring.application.name=the-collector-backend

# Temporary: Disable Custom Security for initial test endpoints routing
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
